use std::collections::{HashSet, HashMap};
use std::iter::once;
use std::hash::Hash;
use std::option::Option::Some;

pub fn part1() {
    let inp = input();
    let i = input_to_sets(&inp);
    let diffs: HashMap<String, HashSet<String>> = i.iter().map(|(k, v)| (k.to_string(), v.iter()
        .fold(v.first().unwrap().clone(), |a, b| b.intersection(&a).map(|x| x.to_string()).collect())
    )).collect();
    println!("diffs {:?}", diffs);

    // println!("original: {:?}", i);
    // println!("diffs: {:?}", diffs);

    let all_ingr: HashSet<String> = i.iter()
        .map(|(k, v)| v.iter().fold(HashSet::new(), |s1, s2| s1.union(&s2).cloned().collect()))
        .fold(HashSet::new(), |s1, s2| s1.union(&s2).cloned().collect());

    let non_allergens = non_allergen(&all_ingr, &diffs, &HashSet::new());
    // println!("non allergens: {:?}", non_allergens);
    let result: usize = non_allergens.iter().map(|x| -> usize {
        inp.split('\n').map(|line|
            line.split(' ').filter(|&s| s.eq(x)).count()
        ).sum()
    }).sum();
    println!("{:?}", result);

    let ingr_all = ingriedient_allergen(&all_ingr, &diffs, &vec![]);
    let result = canonical_list(&ingr_all);
    println!("{}", result);
}

fn canonical_list(arg: &Vec<(String, String)>) -> String {
    let mut result = arg.clone();
    result.sort_by(|x,y| x.1.cmp(&y.1));
    let result: Vec<String> = result.iter().map( |(i, a)| i).cloned().collect();
    result.join(",")
}

fn ingriedient_allergen(ingredients: &HashSet<String>, allergens: &HashMap<String, HashSet<String>>, acc: &Vec<(String, String)>) -> Vec<(String, String)> {
    if let Some(only_one) = allergens.iter().filter(|(k, v)| v.len() == 1).next() {
        let new_allergens: HashMap<String, HashSet<String>> = allergens.iter()
            .map(|x| (x.0.clone(), x.1.iter().filter(|&lis| !lis.eq(only_one.1.iter().next().unwrap())).cloned().collect()))
            .collect();
        let mut new_res = acc.clone();
        new_res.push((only_one.1.iter().next().unwrap().clone(), only_one.0.clone()) );
        ingriedient_allergen(ingredients, &new_allergens, &new_res)
    } else {
        acc.clone()
    }
}

fn non_allergen(ingredients: &HashSet<String>, allergens: &HashMap<String, HashSet<String>>, acc: &HashSet<String>) -> HashSet<String> {
    if let Some(only_one) = allergens.iter().filter(|(k, v)| v.len() == 1).next() {
        let new_allergens: HashMap<String, HashSet<String>> = allergens.iter()
            .map(|x| (x.0.clone(), x.1.iter().filter(|&lis| !lis.eq(only_one.1.iter().next().unwrap())).cloned().collect()))
            .collect();
        let mut new_set = acc.clone();
        new_set.insert(only_one.1.iter().next().unwrap().clone());
        non_allergen(ingredients, &new_allergens, &new_set)
    } else {
        ingredients.difference(acc).cloned().collect()
    }
}

fn input_to_sets(arg: &str) -> HashMap<String, Vec<HashSet<String>>> {
    let pairs: Vec<(HashSet<String>, Vec<String>)> = arg.replace(')', "").split('\n')
        .map(|line| line.split(" (contains").map(|s| s.to_string()).collect())
        .map(|v: Vec<String>| (v[0].split(' ').map(|x| x.to_string()).collect(), v[1].replace(' ', "").split(',').map(|x| x.to_string()).collect()))
        .collect();

    let mut parsed: HashMap<String, Vec<HashSet<String>>> = HashMap::new();
    for (set, p) in pairs {
        for word in p {
            match parsed.get(&word) {
                Some(v) => {
                    let mut mv = v.clone();
                    mv.push(set.clone());
                    parsed.insert(word, mv);
                }
                None => { parsed.insert(word, vec![set.clone()]); }
            }
        }
    }

    parsed
}

fn input() -> String {
//     "mxmxvkd kfcds sqjhc nhms (contains dairy, fish)
// trh fvjkl sbzzf mxmxvkd (contains dairy)
// sqjhc fvjkl (contains soy)
// sqjhc mxmxvkd sbzzf (contains fish)".to_string()
    "qgct fxctfc zbqfz zxdkrx hrqbs hgmsn ndqtf rmn cxfz slzctfh xvj xrqj nslqr bnxl rsprgcj vvchk gfhdct xsbt qbkjvg xtpdql mpvnt ssffbt gtl lxjtns prxmdlz mjlqj clg mrjqg qdtjjz fkxf vzzz qdfpq cqkrhx vbmz ljcvh mvdgf clmxkbn nmqlz vjzc bqrqj sqnbsg tn knprxg rbxz qzqzj qmcrpm grzv (contains wheat, eggs)
jthsmn qdtjjz qkhft slzctfh ksfbnhz rsprgcj tn clg zjtlrq ttqgh rclxmm llqfr kl qdfpq lxjtns cxfz mgx vjzc ncjv vrqb jmrx qmcrpm prxmdlz zsgnd vhbmztr gscdgj mrjqg sxxnb rkgbgn dxzmr nnxmgx cjp qzdpffs tbvh dxldm rxhrpjv jtgsn khqt jgdf jtlfh pdvqs kzpmt nslqr vzzz rmsgmj nkjcr bnxl lqtqm xlkgtc jcs cqkrhx xxhtdkp qnljhd kkhq gmdldb (contains soy, peanuts, sesame)
glx bzxh slrc qhzqq vdlj xmm vjzc dsksm qrnkl xpjd ttqgh qdfpq dtnzp tfrpccb lchdf sjg mgx xkzk qmcrpm jlfm knprxg xngkf mpvnt gfhdct vmcsb cjp zdvr ncjv ssffbt dxzmr xkkjl ltcxqdbm rxdns qdtjjz qpfh clg vzzz gtl prxmdlz jcs mct xsbt lxjtns hgmsn jbpz rxhrpjv fkxf vqbb qckgcc (contains peanuts, fish, sesame)
txhkk mvdgf llqfr clg vbmz tfrpccb rjmk bkzgpg cxfz qdfpq prxmdlz vqbb jmrx kl mjlqj zbqfz sfkf pgzgn qjtrpj jpdxvmv qpfh vrhj zpsbc vjzc ncjv crbxx cklx lxjtns zxdkrx gmdldb jgdf kvzpzvt fkhcbzbk rsprgcj rkgbgn mbllkbf grzv qc pdvqs jrbfkg kkhq qckgcc dxzmr qzdpffs hfjrp ljcvh vzzz fsjbdt qzqzj vsbttl qmcrpm tcnhp qrnkl hlsbn mgx (contains soy, eggs, sesame)
qzdpffs vvchk xtzt drqg tn mzr lxjtns grzv hjg hsfx qnljhd mpvnt zkvlf mmdmtg knprxg xjjk llqfr cklx rmc cxfz gpjkqrq zxjksd zpsbc xkkjl nkjcr mtzqr zsgnd jlrtmv vjzc qdtjjz fpqc crbxx ncjv cqkrhx lzkmdq vhcqpn mct fhtn qqgq xxhtdkp dsksm rxdns vrhj qgct mgx nslqr slg qhzqq jcs vzzz prxmdlz sskfj pgzgn gfhvs kcncjpk pbblp hbkmd clg fsjbdt qckgcc zjtlrq nnxmgx rkgbgn sxxnb tcnhp qmzzgr slzctfh vbmz bqrqj sjg zdxn rxhrpjv tfrpccb bkzgpg rgmlds ltcxqdbm rpmf (contains eggs, sesame)
zdvr zxdkrx gmcm xmm tbvh mct jlfm sfxsj qpfh ltcxqdbm jtlfh qmzzgr fkhcbzbk tfbpk lqkxpxr ssfb knprxg gxnjk dsksm mgx cjjd qckgcc tn gfhvs zjtlrq fhtn cqkrhx tcnhp qc qdfpq bkzgpg bzxh hbkmd rkgbgn lzkmdq hbpsp xkzk pdvqs vhbmztr ssffbt nfzz zsgnd dqf sdcdmn cklx xsrk pjlz ncjv vdlj hfjrp dxldm lxjtns gmdldb qzdpffs xtpdql slg pdfv jncfpc clg qhzqq prxmdlz vzzz dxzmr vvchk pgzgn (contains eggs, nuts, fish)
drqg sfkf kl pjlz bqrqj tcnhp gfhvs bnxl llqfr csdslq jglqz qbkjvg fsrmcx ffpfsv mgx bbltf xqpph ssb vzzz xrqj zdxn dsksm gmcm xngkf lqkxpxr xsbt cxfz xxhtdkp lxjtns vdlj rxdns rmsgmj qmzzgr rbxz jbpz vrhj rkms gtl clg pdfv prhkvr knprxg bqdtr qrnkl mzr gscdgj zpsbc zkvlf fkhcbzbk qzqzj prxmdlz qdfpq txhkk xvj jpdxvmv mjlqj mct rtkk mrjqg mpvnt fxctfc qjtrpj jmrx vbmz hfjrp zxjksd qmcrpm sjg vvchk xmm hlsbn sbkksv cklx jlrtmv sxxnb glx vsbttl jrbfkg mvdgf xsrk vjzc (contains eggs, sesame, nuts)
rmsgmj pdvqs xxhtdkp nmqlz sskfj cxfz xlkgtc jrbfkg ttjvqs tfrpccb xjjk knprxg mct qqgq ltcxqdbm zdvr dsksm pbblp mtzqr slg ncjv ssfb rbxz bnkss zjtlrq gxnjk gpjkqrq tcnhp xctvtxzl lqkxpxr fpqc ffpfsv vrqb jbpz slzctfh cjjd tn qdfpq hlsbn vzzz rtkk lzkmdq gfhdct rkms zkvlf pgzgn vqbb vrhj txhkk bqrqj mjlqj vjzc rmc ksfbnhz dtkcj nzqlgz jcs zdxn xngkf fhtn nkjcr sdcdmn gscdgj jthsmn dqf hrqbs jncfpc bbltf zbqfz clg jpdxvmv xsrk lxjtns khqt mmdmtg lchdf vbmz jmrx sbkksv sqnbsg drqg gmcm nnxmgx rxdns kkhq mzr rxhrpjv ssb bqdtr vvchk (contains shellfish)
mjlqj dxldm bqrqj zxdkrx lxjtns xctvtxzl kvzpzvt jncfpc nnxmgx xtzt ssfb mmdmtg mct ktzlr bzxh xjjk cxfz qmzzgr hlsbn jrbfkg vqbb gmdldb ndqtf zxjksd sqnbsg bnkss sfkf vrhj qnljhd ncjv nmqlz gpjkqrq slg kzpmt drqg xqpph cjp bnxl zpsbc rmsgmj zjtlrq qdfpq clg mvdgf rbxz jmrx qmcrpm jtlfh prxmdlz gtl ssffbt ktgqpk vhbmztr vzzz (contains eggs, sesame, peanuts)
vqbb xngkf nkjcr drqg sfkf xsbt jthsmn prxmdlz clg sqnbsg clmxkbn zdxn tbvh cqkrhx kvzpzvt rxhrpjv vmcsb dtnzp mvdgf qnljhd txhkk lxjtns mmdmtg ttqgh qdfpq pgzgn dqf ssb kkhq ncjv cxfz vzzz rmsgmj ssfb ltcxqdbm jncfpc vjzc csdslq bqdtr prhkvr rkms (contains soy, sesame)
qdfpq hgmsn jbpz sskfj xtpdql ljcvh mct qrnkl qmzzgr lqtqm xxhtdkp rxhrpjv ttjvqs bbltf rxdns vzzz prxmdlz hrqbs vdlj xmm drqg nfzz qckgcc gmcm hbpsp dsksm ffpfsv vqbb mjlqj mmdmtg jlrtmv ktgqpk hbkmd fpqc sfkf dqf ktzlr xkkjl rbxz tfbpk vmcsb tbvh kl gfhvs knprxg nnxmgx ksfbnhz fkxf bqrqj qhzqq bqdtr qjtrpj mbllkbf xsrk qbkjvg lzkmdq ttqgh rjmk gmltxp xjjk lqkxpxr cqkrhx cxfz crbxx vbmz zsgnd lxjtns jgdf hfjrp pdfv clg mpvnt bnkss gbk zxjksd nkjcr sdcdmn (contains wheat)
kl bqdtr mgx jcs nfzz knprxg lqtqm clg slg jglqz gmdldb sqnbsg qmcrpm pgzgn tbvh nzqlgz llqfr tfbpk fxctfc qnljhd cxfz vzzz nkjcr pbblp hfjrp clmxkbn rxhrpjv ncjv bnkss slrc prhkvr qpfh tcnhp xsrk kkhq hrqbs qgct gscdgj vbmz xrqj pdfv sfkf khqt xpjd rjmk lxjtns qdfpq vhcqpn ttqgh bnxl zjtlrq qqgq lchdf jgdf jpdxvmv mmdmtg sdcdmn (contains nuts, peanuts)
vrhj bnxl vsbttl qdtjjz ncjv bbltf mgx xpjd mbllkbf hgmsn xqpph vzzz dxldm tcnhp vhbmztr jthsmn mpvnt prhkvr gbk rxhrpjv ffpfsv clmxkbn rsprgcj qbkjvg tbvh rmc kvzpzvt qsgcg nnxmgx qdfpq xlkgtc rgmlds pgzgn bqdtr vdlj kkhq sqnbsg cqkrhx qgct ttqgh rkms xtzt nmqlz vbmz vmcsb mtzqr nslqr llqfr zxjksd cxfz fxctfc dtnzp slrc grzv nkjcr sdcdmn xtpdql gxnjk lxjtns mvdgf qzdpffs mct csdslq knprxg zkvlf vvchk nzqlgz crbxx pdvqs prxmdlz bnkss ktgqpk ltcxqdbm qrnkl gtl gmdldb jncfpc tn jmrx qckgcc gpjkqrq dxzmr rclxmm rkgbgn bqrqj xjjk (contains sesame, fish)
nzqlgz ffpfsv qjtrpj vjzc mzr bqdtr gmcm kkhq vmcsb vhbmztr ssfb hbkmd rxdns mjlqj knprxg qmzzgr qc tfrpccb cjp vzzz ltcxqdbm tqgjg mbllkbf sfxsj xngkf jtlfh ncjv hfjrp jmrx vvchk rclxmm dtnzp fsjbdt sfkf qbkjvg gmltxp jncfpc clg bzxh xxhtdkp xjjk dtkcj qdfpq bqrqj drqg gfhvs nfzz tfbpk jlrtmv prxmdlz zdvr fhtn sskfj qsgcg lxjtns (contains fish, eggs)
llqfr zsgnd vvchk hjg qmzzgr vzzz jncfpc gxnjk sfxsj fsrmcx zbqfz glx qzdpffs bbltf rkgbgn qc gbk xkkjl xxhtdkp tqgjg jmrx nkjcr slg rjmk vrhj nnxmgx gmcm rxhrpjv ltcxqdbm bqrqj ksfbnhz hbkmd rtkk mbllkbf bkzgpg ssb qjtrpj vbmz zjtlrq kzpmt clg qsgcg bqdtr mgx lxjtns crbxx qhzqq pgzgn sbkksv rgmlds jgdf jlrtmv ncjv ktzlr gpjkqrq cxfz qzqzj bqg dxzmr vhcqpn jpdxvmv pdvqs hrqbs rxdns kvzpzvt fsjbdt lzkmdq jbpz knprxg xsbt kkhq dtnzp qdfpq gfhdct sfkf tbvh cjjd vqbb xjjk (contains sesame, nuts)
qqgq xmm fhtn tcnhp prxmdlz sskfj ksfbnhz tbvh ncjv rkms nkjcr sjg grzv jmrx vhbmztr knprxg pdfv khqt qhzqq cjp zsgnd txhkk xpjd ltcxqdbm cqkrhx fkhcbzbk hbpsp slzctfh qsgcg gmcm tfrpccb jlrtmv qdfpq tfbpk vdlj fxctfc jpdxvmv gpjkqrq clg vhcqpn zkvlf crbxx zjtlrq ssfb ttqgh xqpph qjtrpj rpmf vqbb pgzgn hfjrp vzzz gtl vjzc mjlqj qdtjjz lxjtns qpfh zdxn xtpdql (contains fish, peanuts)
grzv pbblp vhbmztr qjtrpj zsgnd dxldm pdfv rxdns vrhj cqkrhx clmxkbn vsbttl lchdf slzctfh bqrqj vdlj mgx zxjksd ssffbt ncjv mmdmtg sqnbsg vzzz qckgcc jrbfkg lxjtns slg cklx zpsbc jlrtmv pdvqs ffpfsv jncfpc vrqb knprxg qdfpq rtkk dqf rbxz xpjd qc rmn ttqgh zjtlrq tbvh clg hfjrp bqg sdcdmn bkzgpg zdvr mct csdslq qgct gmdldb bnkss qsgcg prxmdlz xrqj dsksm (contains nuts, shellfish, fish)
rtkk jncfpc zxjksd zsgnd clg crbxx sdcdmn vbmz rkms hlsbn xsbt tfrpccb zdvr prhkvr vzzz slzctfh txhkk knprxg drqg slrc rgmlds xxhtdkp lxjtns mct qqgq grzv zpsbc gbk qmzzgr fpqc nnxmgx kl hjg jlfm kzpmt lqtqm xtpdql rmc hbkmd rxdns rmsgmj sqnbsg xqpph rclxmm zkvlf jmrx cklx mrjqg qmcrpm kcncjpk pbblp fkxf ncjv fsrmcx pgzgn xvj sjg rkgbgn cjp dsksm nmqlz zxdkrx sbkksv tcnhp ljcvh prxmdlz gfhvs mjlqj qc ssb cxfz bzxh dtkcj ksfbnhz hfjrp mgx mtzqr bqdtr sskfj cjjd ltcxqdbm fxctfc ktzlr nfzz dqf kvzpzvt (contains shellfish)
rtkk xrqj xctvtxzl gmltxp qzdpffs bqrqj gpjkqrq xpjd xngkf jcs nslqr slzctfh rsprgcj ksfbnhz qdtjjz jthsmn ttjvqs nkjcr xjjk qgct ncjv xkzk ktgqpk mct xlkgtc xsrk sdcdmn hrqbs jrbfkg jglqz vdlj slrc vqbb nzqlgz prxmdlz tcnhp qckgcc zxjksd vzzz bqdtr slg ffpfsv qkhft lqtqm clg dxzmr cxfz jtlfh jncfpc lxjtns gfhdct sjg ljcvh hjg qzqzj dsksm ktzlr knprxg rclxmm kzpmt vrqb rkgbgn sfxsj cqkrhx vhbmztr (contains fish, eggs, peanuts)
kkhq tbvh knprxg qdfpq rpmf rkms mct cjp ttqgh qjtrpj cklx rxdns tn rgmlds mrjqg mbllkbf qnljhd pdfv pdvqs jgdf pjlz ssfb xsbt clg crbxx qrnkl rsprgcj llqfr fxctfc clmxkbn jlfm txhkk hbpsp fsjbdt gmcm lzkmdq nslqr xjjk vzzz kl ssb ktgqpk prxmdlz nmqlz sfkf rmsgmj rkgbgn ssffbt gscdgj lchdf lxjtns gfhvs jncfpc csdslq xpjd qdtjjz hgmsn cxfz (contains peanuts, shellfish)
jlfm knprxg nkjcr slg vzzz fkxf ffpfsv rclxmm rmn ncjv cjjd mbllkbf xxhtdkp rtkk txhkk hsfx mvdgf clg qbkjvg fkhcbzbk sskfj fpqc khqt zjtlrq dqf cqkrhx hrqbs sfkf qdfpq vjzc vsbttl vrqb lqkxpxr cxfz bnxl xsrk hbpsp vqbb kkhq bnkss hfjrp qrnkl lzkmdq zkvlf drqg gfhdct lchdf pjlz lxjtns fsrmcx dxzmr (contains sesame, peanuts)
rxdns qhzqq clg mrjqg ndqtf jrbfkg cqkrhx sdcdmn qdfpq cxfz xvj fpqc xkkjl dxldm bnxl dxzmr fkhcbzbk vjzc hjg qpfh rpmf xpjd mpvnt nkjcr qzqzj drqg jbpz gbk fxctfc jlfm xtpdql bzxh sfxsj zxdkrx ffpfsv hfjrp tfrpccb khqt qc rkgbgn nmqlz rmn ssffbt slzctfh mzr xsbt qckgcc knprxg lxjtns prxmdlz gfhvs bnkss kcncjpk vzzz gscdgj mmdmtg ssfb zsgnd xxhtdkp (contains eggs, nuts, peanuts)
xtzt tfrpccb vrqb rxhrpjv cxfz gfhvs llqfr sqnbsg jlfm rsprgcj tn jncfpc rgmlds csdslq ssfb qdtjjz qmzzgr nslqr rmn fsrmcx gbk rjmk vbmz rkgbgn zsgnd prxmdlz qpfh dqf pdvqs vdlj zjtlrq rclxmm qrnkl qgct vqbb qzqzj rxdns zkvlf zdxn knprxg bzxh gmdldb cklx zxjksd vvchk zpsbc sxxnb lxjtns qdfpq ljcvh jthsmn ksfbnhz gfhdct zbqfz mjlqj ssb kzpmt vzzz fxctfc xngkf nkjcr sfkf kkhq jgdf clg bqdtr xxhtdkp (contains wheat, nuts)
cjjd ttqgh jthsmn cxfz dtnzp ksfbnhz slrc rtkk rbxz hjg clg tfbpk tqgjg kl lxjtns tn ncjv bnkss jtlfh xkzk vrhj crbxx ssfb zpsbc gmcm qc jncfpc mzr vbmz gscdgj qsgcg knprxg xqpph bnxl hfjrp nzqlgz qnljhd pgzgn vmcsb xmm qdfpq cklx ffpfsv sxxnb vzzz (contains nuts)
pjlz zbqfz xsbt cxfz vsbttl sbkksv mtzqr dxldm lqkxpxr vqbb gtl mjlqj vhbmztr slg glx khqt mmdmtg nslqr zkvlf cjjd ncjv tfrpccb xkzk xlkgtc kcncjpk jgdf hbkmd mbllkbf prhkvr kl vzzz rgmlds rsprgcj gbk lxjtns dtkcj bbltf rkgbgn knprxg prxmdlz qdfpq rpmf jtlfh xvj jtgsn vrhj bqdtr vvchk bqrqj jlrtmv gfhvs hsfx xtpdql cqkrhx xjjk (contains soy)
rmsgmj txhkk slg nfzz mmdmtg ssb lchdf mct csdslq pgzgn qgct xmm bnkss ljcvh gbk jmrx clg zsgnd vvchk ktgqpk bzxh fxctfc slzctfh tcnhp kcncjpk vrhj nkjcr cqkrhx clmxkbn gmltxp fpqc xtzt rclxmm sdcdmn qbkjvg dxldm dxzmr fkxf vqbb vhcqpn qsgcg lqtqm jbpz lzkmdq mtzqr xtpdql qc cjp sjg bkzgpg bqg rgmlds qdtjjz qckgcc prxmdlz mpvnt knprxg xngkf mjlqj nmqlz xxhtdkp zpsbc mrjqg qdfpq rmn cklx jpdxvmv glx xctvtxzl sfkf bqrqj zbqfz zkvlf rxdns gfhdct sskfj mgx qhzqq kvzpzvt cxfz gpjkqrq gmcm jglqz xkzk lxjtns xpjd rbxz xvj grzv hbkmd slrc dtkcj ncjv xqpph zdxn (contains shellfish, wheat, fish)
ttqgh qzqzj lxjtns rbxz xpjd dxldm fsrmcx pjlz nslqr khqt crbxx pbblp pdfv hrqbs mbllkbf rmc zbqfz prxmdlz ncjv llqfr gxnjk ltcxqdbm qdfpq gfhdct dsksm vhcqpn ssb cjp nmqlz vrqb cjjd slzctfh vqbb zsgnd rmsgmj ktzlr hfjrp cxfz vvchk qbkjvg gscdgj txhkk kcncjpk zpsbc mtzqr sxxnb jmrx knprxg nfzz vzzz fhtn rkms jncfpc nzqlgz jgdf ksfbnhz qgct (contains nuts)
ltcxqdbm clg xkzk jgdf clmxkbn bnxl pdfv nslqr ncjv rpmf ttjvqs lzkmdq vzzz jcs qnljhd hrqbs gscdgj txhkk tqgjg kvzpzvt knprxg fxctfc drqg dsksm ttqgh fkhcbzbk xsrk sjg gmcm xtpdql prxmdlz gfhvs qdfpq kcncjpk ktzlr qjtrpj cklx gpjkqrq jtgsn cxfz dxzmr qzdpffs sbkksv ssb sfkf jmrx nfzz vvchk xngkf gfhdct vhbmztr tn vrhj fkxf xkkjl mmdmtg mct kl lqkxpxr (contains soy, shellfish)
lzkmdq dsksm qzdpffs xctvtxzl nmqlz xxhtdkp lqkxpxr hjg zpsbc nkjcr qhzqq bzxh rsprgcj zxdkrx nzqlgz hbpsp dqf xsbt jpdxvmv qkhft csdslq xmm mbllkbf xsrk jbpz prxmdlz slrc qdfpq gmcm glx prhkvr zsgnd bqg fpqc clg zjtlrq nnxmgx pgzgn mzr mvdgf ncjv rgmlds knprxg dxzmr xvj gmltxp lxjtns mpvnt xtzt xtpdql zdxn kcncjpk gbk cxfz fxctfc sskfj sdcdmn bbltf vvchk jthsmn jmrx gmdldb cklx (contains peanuts, wheat)
rtkk kl fsrmcx prxmdlz lqkxpxr hfjrp fpqc jmrx vzzz xtpdql gscdgj ltcxqdbm zxjksd bnxl lxjtns bqdtr mrjqg qgct xlkgtc bnkss txhkk qkhft hsfx cjjd csdslq kzpmt gmdldb ljcvh clmxkbn xmm jglqz vrhj rmc xkkjl knprxg tfrpccb jtlfh lchdf rxhrpjv vjzc qqgq sxxnb qckgcc fxctfc tbvh xkzk jlrtmv qbkjvg rbxz hbkmd jthsmn bbltf nslqr mgx clg cxfz jlfm gtl kcncjpk cjp gpjkqrq qzdpffs xsbt xjjk qdfpq tfbpk ktzlr nnxmgx xxhtdkp prhkvr qrnkl fhtn cklx sqnbsg slg glx (contains wheat)
prhkvr tfbpk prxmdlz sdcdmn xrqj mvdgf sbkksv lxjtns hbpsp fsjbdt llqfr rpmf zpsbc rbxz mjlqj fsrmcx gmltxp mrjqg jtlfh bqdtr jpdxvmv tbvh bqrqj ndqtf bnkss sfxsj nkjcr xvj rclxmm sxxnb hgmsn knprxg qdfpq mmdmtg mgx jlfm cqkrhx fpqc zxjksd bkzgpg fkxf xpjd clmxkbn ncjv clg xqpph xsbt fhtn qzqzj nnxmgx lchdf bnxl gmdldb qnljhd khqt rmn vzzz dxzmr (contains nuts)
cxfz mjlqj lxjtns kvzpzvt mrjqg qmcrpm clg ssffbt ndqtf rmsgmj dqf ttjvqs ksfbnhz tcnhp gmcm zsgnd hbpsp xtzt qjtrpj jbpz slzctfh qpfh hjg xjjk knprxg fkhcbzbk prhkvr cqkrhx lqkxpxr zpsbc qnljhd xkkjl lchdf xtpdql vzzz sjg ncjv bkzgpg pdfv sdcdmn cjjd ltcxqdbm vdlj csdslq nnxmgx mct jtgsn qckgcc bbltf jlfm bzxh dtnzp tfbpk gpjkqrq xqpph qc bqrqj vvchk ssfb glx lqtqm xngkf nslqr qzqzj gbk sfxsj prxmdlz xkzk (contains soy, nuts, peanuts)
slzctfh mbllkbf xvj sfxsj xtzt rmc rkms qmcrpm hgmsn dsksm knprxg rsprgcj jpdxvmv qrnkl rxhrpjv rbxz xqpph sjg xctvtxzl mzr lxjtns ncjv dqf prxmdlz nkjcr nmqlz hrqbs gmltxp gxnjk sbkksv mtzqr mvdgf clg ndqtf jbpz kvzpzvt cjjd hfjrp gmcm jrbfkg xrqj zpsbc gpjkqrq bzxh qzqzj qdfpq qsgcg hbpsp hjg qmzzgr mct mgx qbkjvg jgdf drqg fxctfc dxzmr cklx qpfh jtlfh rxdns dtnzp xxhtdkp jtgsn zbqfz jlfm lzkmdq vzzz nnxmgx xtpdql xkzk vhbmztr dxldm gfhvs jncfpc qjtrpj ttjvqs ssfb bqg (contains fish)
prxmdlz mtzqr tfbpk xqpph hrqbs clg zxdkrx lchdf vzzz gmcm ksfbnhz dtkcj mbllkbf tbvh sqnbsg dtnzp qdfpq kkhq dxldm mzr xngkf qkhft jglqz hbkmd zkvlf ncjv cqkrhx xmm kzpmt gbk qhzqq mmdmtg xxhtdkp jpdxvmv kcncjpk mgx cxfz ktzlr hlsbn prhkvr lxjtns xpjd cjjd gpjkqrq sxxnb qjtrpj qqgq sbkksv mvdgf jtgsn slg ktgqpk fhtn rtkk rxdns qrnkl ssb dxzmr mct lzkmdq fsjbdt sjg rxhrpjv rkgbgn xctvtxzl mpvnt (contains wheat)
pdvqs rjmk clg mgx zdxn qzqzj qzdpffs rpmf jcs zxdkrx jtlfh rbxz kkhq rgmlds ljcvh sqnbsg dsksm zkvlf bqg qhzqq tn hsfx lchdf qgct lqtqm jthsmn lxjtns xctvtxzl nfzz hbkmd slrc pjlz jtgsn vzzz mjlqj kzpmt pbblp knprxg mrjqg txhkk mct ssfb bqrqj clmxkbn rmsgmj jlfm mmdmtg xsrk pgzgn prxmdlz jncfpc hrqbs bnxl nkjcr zjtlrq xrqj mvdgf gmcm tcnhp lqkxpxr zbqfz zpsbc gxnjk fsjbdt gbk kl hgmsn dqf rsprgcj vqbb qmcrpm jmrx qsgcg tbvh fsrmcx hlsbn lzkmdq slzctfh ssffbt gfhdct qc xkzk vvchk cxfz qmzzgr fhtn vrqb rkms kcncjpk pdfv gscdgj xtpdql cjp sfkf vsbttl sjg qdfpq (contains sesame, soy, nuts)
cklx vzzz fhtn ncjv hgmsn xkzk nslqr rmn ffpfsv fpqc qmcrpm zxdkrx gfhvs sskfj rxdns cqkrhx qjtrpj mvdgf xmm jncfpc vsbttl kl ssfb xsbt zjtlrq gmltxp mzr jtlfh ktgqpk knprxg xxhtdkp nzqlgz clg pdfv drqg qmzzgr lxjtns kkhq rgmlds glx bnxl qsgcg jbpz hlsbn qdfpq cxfz (contains shellfish)
kvzpzvt qgct mvdgf hgmsn jrbfkg qdfpq ssffbt gfhvs prhkvr clg bbltf rbxz lxjtns vzzz dsksm tqgjg txhkk slg gbk crbxx rsprgcj qnljhd qzqzj rmc vrhj hrqbs jgdf qbkjvg vqbb gmcm zxjksd khqt rclxmm ksfbnhz jtgsn mjlqj ssb gmdldb xlkgtc ktzlr ssfb qdtjjz cxfz knprxg rmn xmm ffpfsv vdlj qqgq bnkss xkzk ncjv glx mrjqg bqdtr pdfv lqtqm bqrqj dxldm nzqlgz gfhdct xpjd tfbpk vbmz jncfpc lchdf kkhq (contains nuts, fish)
bqrqj bqdtr vzzz jthsmn vmcsb fsrmcx ncjv xkkjl xqpph slg sdcdmn ssffbt gscdgj gfhvs xlkgtc zkvlf drqg mvdgf hbkmd nzqlgz dxldm slrc qc cjjd vjzc lxjtns zdxn rpmf vdlj xctvtxzl xvj tfrpccb jtgsn sxxnb bbltf kkhq fpqc clg kvzpzvt xtzt qdfpq nnxmgx cklx mrjqg xsrk ttjvqs lchdf qmcrpm kcncjpk nslqr rmc vhcqpn cqkrhx prxmdlz jrbfkg lqkxpxr rsprgcj bzxh lzkmdq ffpfsv vrhj cjp qrnkl qzdpffs vhbmztr hfjrp tcnhp dxzmr fxctfc jgdf rmn mgx rkgbgn gmltxp lqtqm jmrx kl vrqb ltcxqdbm fhtn knprxg (contains peanuts)
gmcm xxhtdkp cqkrhx lqtqm vzzz jpdxvmv grzv ncjv sskfj dxldm kzpmt zdxn zbqfz rclxmm fkhcbzbk vvchk cxfz prxmdlz lqkxpxr vjzc clg jgdf vrqb rsprgcj nzqlgz fhtn jmrx pjlz bnxl bnkss qmzzgr fxctfc qrnkl lxjtns qdfpq slrc slg tcnhp nfzz mbllkbf hlsbn kkhq zxdkrx gmdldb gscdgj (contains sesame, wheat, shellfish)
gxnjk lqkxpxr kvzpzvt vzzz cqkrhx jrbfkg lxjtns xtzt jcs qzdpffs txhkk kzpmt xkkjl vrqb mtzqr fkhcbzbk jtgsn mct prhkvr rmsgmj sdcdmn qkhft ndqtf mjlqj gtl tfbpk mgx jglqz ktgqpk zxjksd xrqj gfhvs knprxg clg hbkmd xmm vjzc rxhrpjv rmc vmcsb nfzz xpjd cjjd sjg ssb fpqc qdfpq llqfr jthsmn vqbb rkms ktzlr ncjv jncfpc qsgcg sfkf cxfz xngkf xxhtdkp glx qmzzgr hrqbs zpsbc bnkss dxldm vbmz tbvh cjp qzqzj (contains soy)
pdfv bkzgpg lchdf dsksm rkms vhbmztr ttjvqs slrc csdslq mtzqr mzr qrnkl slzctfh vhcqpn ndqtf bqdtr ncjv gfhvs dxldm qdfpq bqg sdcdmn nmqlz xtpdql prxmdlz dtkcj rbxz rjmk qc qkhft kkhq ffpfsv jtlfh vrhj vzzz fxctfc rmc mct sqnbsg pdvqs xkkjl dqf rmsgmj lxjtns rtkk jlrtmv jbpz jrbfkg zdvr nslqr hlsbn fsjbdt jncfpc nzqlgz llqfr sfkf ttqgh gmcm qnljhd pjlz ljcvh mgx fkhcbzbk gpjkqrq clg qsgcg vrqb xrqj cxfz jgdf dxzmr tcnhp rxhrpjv tbvh ktzlr (contains wheat, soy, shellfish)
tn bzxh bqrqj csdslq jlfm jtlfh qdtjjz bnxl jthsmn gmcm lxjtns kvzpzvt jpdxvmv xjjk nmqlz rgmlds hlsbn khqt jlrtmv qbkjvg prxmdlz bqg nkjcr vzzz jbpz knprxg qckgcc nfzz pbblp hgmsn hfjrp ktzlr ktgqpk hbkmd qmcrpm gxnjk xsbt qjtrpj fsrmcx gmdldb xctvtxzl cjp cxfz jtgsn rkms vvchk qdfpq rjmk sfkf rmsgmj xngkf zxdkrx mvdgf clg bkzgpg lzkmdq hjg (contains sesame)
kkhq crbxx bqg rkms ncjv rclxmm gfhvs lxjtns vzzz bbltf kcncjpk jncfpc jlrtmv dsksm slg mjlqj xngkf fpqc kl cjjd sdcdmn knprxg grzv rmc lqkxpxr clmxkbn vvchk qzdpffs ksfbnhz zjtlrq bqdtr bnkss xsbt fsjbdt rxdns rjmk slrc zsgnd cxfz xjjk bqrqj bkzgpg vdlj qbkjvg xpjd clg prxmdlz vjzc rbxz sjg rtkk ktzlr sfxsj jbpz khqt qjtrpj pjlz fkhcbzbk ttqgh ssfb ffpfsv xctvtxzl mpvnt rmn ssb hlsbn vrhj rxhrpjv qmzzgr rkgbgn (contains fish, soy)
rmsgmj ttqgh jmrx vrqb xlkgtc csdslq rjmk jncfpc vjzc qnljhd knprxg ssffbt zxjksd ltcxqdbm slzctfh vdlj pbblp rgmlds xrqj fsrmcx sdcdmn lchdf xkzk sbkksv cjp sxxnb cxfz jtlfh clg bzxh gscdgj khqt cqkrhx pdfv nmqlz pgzgn vsbttl gfhdct qc qhzqq xmm gxnjk zkvlf rkgbgn jgdf xctvtxzl zxdkrx rmn nkjcr mgx vqbb mzr prxmdlz bnxl cklx ncjv dqf qpfh rmc hbpsp lxjtns clmxkbn mct ljcvh ttjvqs xxhtdkp pdvqs vzzz qdtjjz (contains shellfish, fish)
cjp clg xsrk gxnjk hbkmd qzqzj mzr rmsgmj mtzqr qgct qmzzgr vdlj hjg bzxh nslqr drqg dtkcj prxmdlz fpqc fkxf tfrpccb csdslq mbllkbf mgx hlsbn knprxg gfhvs vzzz txhkk cqkrhx xjjk jlfm rpmf kl ncjv lxjtns nkjcr rmn qrnkl hsfx qpfh qdfpq fhtn zkvlf qbkjvg rxhrpjv qqgq hfjrp xctvtxzl rkgbgn ttjvqs jtgsn (contains nuts)
zkvlf rclxmm hlsbn gpjkqrq qqgq dxzmr xlkgtc hbpsp zpsbc tfrpccb gscdgj sxxnb ttqgh rxdns lqkxpxr fkhcbzbk mct bnkss prxmdlz rmsgmj qmcrpm kzpmt jrbfkg ncjv vzzz slzctfh xctvtxzl dxldm hsfx ssfb qsgcg cxfz sskfj xkkjl fhtn gxnjk xtpdql nmqlz vbmz ffpfsv jtlfh cklx gmcm nslqr llqfr qzdpffs rkgbgn sbkksv rtkk tqgjg clg nkjcr pgzgn pdvqs vrqb sfxsj lxjtns jgdf qdtjjz prhkvr pbblp knprxg vqbb qnljhd khqt jbpz vsbttl drqg qhzqq (contains soy, sesame, peanuts)
vhbmztr bqrqj jtlfh gmdldb xjjk jlrtmv tqgjg gfhvs ndqtf rgmlds sdcdmn fsjbdt zbqfz ltcxqdbm hbpsp jbpz dqf sxxnb rtkk ncjv prxmdlz sfxsj llqfr rkms cxfz xtzt glx mpvnt xctvtxzl zxjksd gtl zxdkrx knprxg kzpmt pjlz khqt qdfpq tcnhp bqdtr fkxf vjzc mjlqj fxctfc lzkmdq zsgnd clg pbblp kvzpzvt qjtrpj jncfpc nmqlz ljcvh vzzz fsrmcx (contains soy, nuts)
rxdns mtzqr ttqgh dtkcj tn knprxg xqpph qbkjvg nzqlgz hbpsp ncjv dtnzp rbxz jrbfkg ssfb gmcm qckgcc xsrk pbblp qmzzgr sfkf jmrx cjjd rkgbgn fpqc zxjksd gmltxp cqkrhx glx xkkjl sdcdmn gbk jtlfh gscdgj cxfz lxjtns gfhvs jgdf tqgjg xvj vsbttl qc qgct mgx rxhrpjv gpjkqrq qzdpffs prxmdlz xsbt qzqzj xtzt ssb zkvlf vzzz mrjqg qdfpq qrnkl dsksm ljcvh nfzz xngkf bnxl lchdf kvzpzvt rmn khqt ndqtf hrqbs xjjk qnljhd ksfbnhz mmdmtg mvdgf xlkgtc bkzgpg mbllkbf (contains wheat, soy, nuts)".to_string()
//     "cdblnb txts scljtv dsvl ksdgk zbkbgp jflb gxhc chjx rnptcf hpvzlb hxxb gcc rrbk lzpcq dpk rmrmhb clbqr jvpsllhl lbvgfq lhgkrc kmjvr dbkz pctjm mxd nqkggbpq dtpkz vjbmbz hk ljkdr nvbrx bgzm xplz flxvrh qxmrqb zlc bgqg rvvcm dskjpq dgms xzb bhzqc xbhmf jrfzs jbvhl xzgst nkn lrhtp khqsk gtjhr grkrz mvbxt lkrnkm qsbsr bcpgx hplt jdcvff cdqrg pgnpx ttmr (contains dairy, sesame)
// hdfrg rvvcm kqpbzn ksj dcgpsq bgzm rrbk dsvl pctjm dbkz rmbk cdblnb spfzpm ckptp rzvpm gdhpvgz vjbmbz jmtzqjs rzpdmp khqsk jbmq ttmr nkn xhqsl hk nqkggbpq lhgkrc vhhj srmsh xrvhc glpmssg bhzqc snjbct vcfxs flxvrh zbkbgp jzdhlj dgms drfgh hplt zstptg kjdrd zcxfj lzpcq qnzljfj cjgm krllr vzsjm mdzbsft cljq xhdq hdkc fhmgrhg zxtgf pgnpx nvbrx mxd qsbsr vvcnht msfxp pnhrz scnlb tjm skxd nhqtzkn lmn ksdgk zkkxgzm crfvzpt tvdqr xplz cdqrg xzb llfdjz xtzhq (contains wheat, dairy)
// kjdrd gcllv rckbqrc ffssl fxlbcb ztvfvhz nvbrx vgbl dskjpq rtvgv hmqhpzr pgnpx jvpsllhl xzb srmsh glpmssg cdqrg vjbmbz hk zcxfj lrnxgns ttmr dgms tvdqr rzvpm lrhtp hplt kmjvr dzdgl khqsk lhgkrc zbkbgp jrfzs gxhc lbvgfq txts zkkxgzm tjfgc cljq cdblnb gpzq spfzpm hxxb jphll zxtgf qpnt krllr (contains soy, sesame, peanuts)
// jvljzbh sbjnrn jvpsllhl ktlttm msfxp hk sxmsxx jdcvff mvbxt dzdgl xtzhq blkh hdfrg flxvrh rmrmhb vgh jflb zbkbgp xhqsl nvbrx cbshx ksdgk srmsh pgnpx kmjvr dgms bzjmn fnsjrp ndnq nkn dskjpq ljkdr xzb bgqg fzmzs nsgpf zcxfj cljq vcfxs gcc jtq htk krllr dcgpsq gpzq pclzcd (contains wheat)
// jf jzdhlj scljtv fzhvcz ltxf lkrnkm zkkxgzm xnhgg ttmr lrnxgns xzgst cdqrg pgnpx vgh nvbrx pctjm qvqf sbjnrn ckptp zbkbgp dskjpq hk dgms mxd khqsk qxpmkdp tjm smjk kqpbzn fhhcv bcchptf pgxzdxf gpzq glpmssg pnhrz xplz mvbxt xzb bgqg gcj msfxp ksdgk jvrn flxvrh jlpzn ksj vxqrj vzsjm xbngqsv nsgpf rvvcm ktlttm xrvhc qnmt gcllv jdcvff (contains wheat, dairy, soy)
// xbngqsv smtthp khqsk cdqrg bcchptf fhhcv jmrdr jdcvff skkn jf tvdqr jtq glpmssg jlpzn gcc qxmrqb sbtkm pdmg xzb ztvfvhz zbkbgp dgms zstptg txts flxvrh scnlb spnzjj pgnpx mcmr vgbl lqb krllr rnptcf hmqhpzr gdvts srmsh gdhpvgz lzpcq skxd ltxf ksdgk mvbxt dskjpq (contains fish, peanuts)
// jzdhlj mcmr hdfrg ksdgk dskjpq kcck lzpcq fhmgrhg tlfjpc srmsh tjfgc msfxp pclzcd chjx zkkxgzm khqsk frsvq jlpzn nvbrx cvv cdblnb txts lqb skxd mdzbsft kmjvr pgnpx hpvzlb hdkc sklm zcxfj kkggp nql ktlttm tvdqr lrhtp jdcvff scljtv blkh jflb mhzdz rtvgv nsgpf xzb fzmzs (contains fish, eggs, shellfish)
// mdzbsft khqsk bzjmn xzb lmhqv skxd jdcvff pgnpx msfxp xplz mcmr nqkggbpq spfzpm zcxfj lbvlp ktlttm mhzdz vgh hmqhpzr fhhcv jtq ksdgk sklm jffhm ztvfvhz lrnxgns qxpmkdp jlpzn sbtkm sbjnrn jvljzbh cljq tjm ljkdr clbqr ckptp cvv bgzm skkn zstptg jbmq pdmg gcllv vzsjm crfvzpt hk cprbsmpx llfdjz kkggp pnhrz qrvdjvg rzpdmp nvbrx lkrnkm zbkbgp scljtv mvbxt fxlbcb srmsh (contains shellfish, dairy, soy)
// rckbqrc mcmr nql grkrz cljq hplt blkh hdkc fnsjrp pchzb tvdqr jmrdr dcgpsq hk qrvdjvg xqxgx cvv spnzjj xzb scnlb zcxfj nhqtzkn rzvpm jdcvff gpzq pdmg qsbsr zlc ztvfvhz lmn htk frsvq ksdgk jffhm ndnq mxd vvcnht qxpmkdp jbmq ktlttm zdjcvfc jvpsllhl nkn crlzb llfdjz kpcv hdfrg xplz xnhgg ksj nvbrx hpvzlb gdvts jmtzqjs snjbct pgxzdxf dtpkz zbkbgp sbtkm zstptg kcck zkkxgzm srmsh chjx jphll tjm lrhtp vcfxs khqsk msfxp bcchptf dskjpq hmqhpzr crfvzpt rrbk rtvgv dpk jflb gcc jbvhl flxvrh nqkggbpq ljkdr smtthp cjgm txts kqpbzn kkggp (contains peanuts)
// skxd tjfgc tvtsbxb zbkbgp jrfzs gpzq gcc lqb kkggp rmrmhb kjdrd spfzpm blkh xnhgg kmjvr qnmt qvqf jdcvff cjgm gcj gcllv vhhj nvbrx srmsh sbjnrn jmtzqjs crfvzpt ksdgk glpmssg zstptg dskjpq flxvrh qnzljfj dgms bgzm rrbk gbtss txts scnlb clbqr xzb jphll khqsk dzdgl xrmx lmn (contains eggs, wheat)
// rmbk glpmssg hdfrg lmhqv vgbl lkrnkm ztvfvhz dcgpsq vxqrj kkggp bcchptf dpk hxxb ksdgk jdcvff llfdjz crlzb fzhvcz ksj lrhtp gbtss qxpmkdp pgxzdxf zbkbgp tvdqr nvbrx rnptcf khqsk vcfxs gpzq ltxf rckbqrc nqkggbpq ktlttm vrssb ttmr krllr bhzqc mdzbsft mxd pknvxsb jvpsllhl jmtzqjs zvth nql bgzm qnmt msfxp vhhj bgqg sbjnrn zstptg jrfzs djjk spfzpm srmsh snjbct dskjpq kjdrd pgnpx jf cljq qxmrqb tzbrg jflb cdblnb rzvpm hplt (contains sesame)
// jbvhl dcgpsq bgqg lbvlp ksdgk jmtzqjs sklm gpzq thfqk hk jmrdr srmsh ffssl qsbsr dskjpq jvljzbh nhqtzkn nvbrx clbqr rzvpm jffhm dbkz hdkc crfvzpt jphll sbtkm zbkbgp kkggp nql zstptg cbshx qnmt ltxf tnjnr msfxp vxqrj gxhc bcpgx mxd blkh vjbmbz xqxgx bgzm chjx glpmssg skxd pgxzdxf pgnpx jzdhlj sbjnrn vgh vgbl xrmx zkkxgzm xzb pknvxsb (contains eggs)
// qrvdjvg vjbmbz hplt ksdgk flxvrh mlvdvc llfdjz ktlttm mxd xzb kcck pctjm cdblnb km ksj bcchptf zcxfj jbmq pgnpx cprbsmpx jbvhl xhdq hdfrg xbhmf gtjhr gdvts bgqg vzsjm msfxp lqx jf gcllv ckptp scljtv zdjcvfc nkn lzpcq tjfgc mvbxt lrnxgns rzpdmp frsvq xrvhc zkkxgzm nqkggbpq dtpkz srmsh jtq djjk cljq gxhc bgzm zbkbgp tvtsbxb sxmsxx qxpmkdp pgxzdxf khqsk sbtkm jvrn dskjpq (contains dairy)
// cdblnb tvdqr nqkggbpq jvljzbh tjfgc cpzzfpz hdfrg lzpcq dskjpq ksdgk vvcnht xhdq vgh dgms xnhgg tjm jf krllr frsvq vcfxs ztvfvhz bgzm rzpdmp jtq crfvzpt grkrz qnzljfj gcllv gbtss pgnpx gtjhr srmsh zstptg qnmt cdqrg cprbsmpx rrbk bhzqc km lbvgfq kqpbzn bgqg xplz zvth mxd djjk pchzb hxxb hk qrvdjvg ljkdr vzsjm xqxgx khqsk dtpkz rmrmhb qvqf pclzcd vrssb pctjm stfmsqc ffssl lbvlp fjqlm gxhc sbtkm dpk flxvrh jmtzqjs lrnxgns skxd jbmq xzb nvbrx (contains dairy)
// htk xrvhc pgxzdxf scljtv scnlb rrbk jmrdr ksdgk ttmr pclzcd drfgh hk jrfzs dgms ljkdr mcmr lzpcq vnrmm zbkbgp llfdjz vhhj jtq vzsjm skxd ndnq lmn bcpgx nkn dbkz sxmsxx cdblnb pdmg kttg jvpsllhl srmsh qxmrqb spnzjj djjk snjbct dskjpq zkkxgzm lqx gdhpvgz pnhrz xbngqsv qnmt fzmzs sbjnrn xlchb thfqk pgnpx khqsk spfzpm nvbrx (contains eggs, peanuts, fish)
// thfqk txts vcfxs pchzb dskjpq tvtsbxb jrfzs xlchb zcxfj rzpdmp zbkbgp smtthp lmhqv zxtgf xnhgg qrvdjvg ckptp htk ktlttm nvbrx srmsh cdqrg hk khqsk jlpzn fhhcv xbhmf vhhj cjgm rckbqrc dgms nql vjbmbz sbtkm bhzqc crlzb xhqsl jzdhlj xhdq jphll lhgkrc mcnzq pgnpx gdhpvgz xzb (contains shellfish)
// pgnpx tzbrg mcmr kmjvr ksj zcxfj sbtkm fnsjrp scnlb nql pgxzdxf bzjmn jvpsllhl xrvhc fzmzs jvrn xhqsl vhhj lrhtp cjgm dpk rmbk xzb pchzb rzvpm xzgst nqkggbpq gcllv xbhmf drfgh hmqhpzr zxtgf jzdhlj xnhgg pclzcd cdqrg gdhpvgz khqsk km jphll ltxf rckbqrc rnptcf vgh hplt hxxb nvbrx qnmt jmtzqjs skxd qnzljfj crfvzpt fxlbcb bgqg rzpdmp srmsh chjx ljkdr htk mdzbsft crlzb txts pctjm vrssb dskjpq jvljzbh gpzq pnhrz xhdq ztvfvhz qxpmkdp lbvlp gcc sxmsxx spfzpm mxd cprbsmpx tvtsbxb kttg zvth krllr frsvq pdmg llfdjz ksdgk (contains sesame, shellfish)
// hk jvrn bcpgx ndnq cdblnb pknvxsb zvth gdhpvgz vgbl khqsk jrfzs jphll jffhm bgzm drfgh tvtsbxb skkn dskjpq ksdgk kjdrd hdfrg jbmq kcck xrvhc zkkxgzm kttg qrvdjvg ksj dbkz srmsh dsvl gcllv fnsjrp vgh rrbk fhmgrhg lqx nvbrx zdjcvfc pgnpx qnzljfj xzb scnlb rzpdmp (contains eggs)
// dtpkz jlpzn vjbmbz xzgst hplt mvbxt pclzcd kmjvr lmhqv jflb zbkbgp rzpdmp pdmg dskjpq qxpmkdp zdjcvfc xnhgg jtq fhhcv zkkxgzm bcchptf nvbrx khqsk tlfjpc xqxgx blkh lbvlp jbmq fjqlm fxlbcb djjk xplz ksdgk dpk pnhrz jvrn tjfgc tzbrg pchzb xzb xbhmf tvtsbxb kjdrd rckbqrc gdhpvgz srmsh (contains fish, shellfish)
// mcnzq skkn pgnpx hplt rzpdmp jbvhl crfvzpt qnzljfj dpk srmsh lzpcq jzdhlj pdmg mhzdz fnsjrp hxxb jffhm krllr vnrmm vvcnht bgzm clbqr khqsk vgbl jvpsllhl xrvhc stfmsqc msfxp bcchptf xqxgx glpmssg djjk tjfgc cprbsmpx jmrdr nvbrx xbngqsv pgxzdxf lrnxgns chjx pclzcd jdcvff rckbqrc rmbk lhgkrc gbtss fxlbcb zvth nqkggbpq frsvq crlzb xplz xnhgg pknvxsb zbkbgp blkh jvrn dskjpq sklm cvv nsgpf ksj rrbk nhqtzkn ffssl ksdgk qxmrqb lkrnkm mcmr (contains eggs)
// sbtkm pnhrz jmrdr pchzb tnjnr grkrz skxd dsvl hdfrg rtvgv rnptcf crfvzpt dskjpq bhzqc jvpsllhl xlchb nhqtzkn llfdjz msfxp cjgm vgh tjfgc xzb nsgpf zxtgf scnlb tzbrg frsvq jflb drfgh lrnxgns cdblnb hdkc mcmr stfmsqc pgxzdxf jphll fhhcv rmbk mlvdvc gcj mcnzq ksdgk lbvlp fhmgrhg tjm rzvpm qnzljfj pgnpx lmn qvqf nvbrx vjbmbz xhdq zbkbgp djjk hxxb ksj fxlbcb jffhm dcgpsq lhgkrc cljq kmjvr chjx jbvhl snjbct smjk ktlttm khqsk (contains peanuts)
// lzpcq jzdhlj gcllv jvpsllhl kttg kjdrd jvrn nvbrx cljq hplt jphll lrnxgns bgqg msfxp pdmg gxhc jf smtthp gcj gdvts clbqr xrvhc ztvfvhz qsbsr lqx pgnpx hdfrg cvv zstptg jtq scljtv rzpdmp khqsk zbkbgp vxqrj dskjpq rmrmhb bgzm bcchptf jmtzqjs krllr llfdjz ndnq fhmgrhg djjk cdqrg lmhqv rckbqrc zdjcvfc xnhgg gdhpvgz qnmt lmn jlpzn skxd xzb mxd cprbsmpx ksj mlvdvc jdcvff pgxzdxf gbtss chjx vvcnht jbmq spnzjj drfgh vcfxs pctjm zcxfj ttmr jflb flxvrh hk pclzcd ksdgk cpzzfpz ljkdr xplz (contains shellfish, soy)
// pgnpx jvrn jbvhl jflb jffhm mcmr rvvcm qnmt lrnxgns txts jrfzs skkn sxmsxx kpcv bhzqc htk khqsk ltxf fhhcv blkh xplz mcnzq cpzzfpz fhmgrhg dcgpsq ksdgk jmtzqjs xzb gcllv lrhtp cjgm qqzqd mxd hpvzlb kqpbzn gdvts zcxfj bgqg rmrmhb srmsh jphll bcpgx xtzhq krllr jmrdr zbkbgp nvbrx ljkdr lqb smjk gtjhr bcchptf tjfgc dsvl kjdrd (contains shellfish, wheat)
// kkggp bzjmn jvrn kcck smjk stfmsqc grkrz blkh vgh zdjcvfc xbhmf lhgkrc gxhc nhqtzkn xplz khqsk gdvts lzpcq zbkbgp jrfzs km vvcnht dskjpq xzgst zcxfj dtpkz lqb dsvl qqzqd jdcvff srmsh lrhtp rtvgv nsgpf rvvcm nqkggbpq gbtss fxlbcb pgnpx crlzb xqxgx vnrmm llfdjz qsbsr xzb flxvrh sbjnrn mcmr mvbxt scnlb nvbrx tzbrg lmn vgbl dzdgl qnmt qxmrqb ksj kttg gcj nkn cdqrg kmjvr pdmg fhhcv spnzjj glpmssg bcpgx qpnt ztvfvhz cpzzfpz mdzbsft rzvpm rmbk vcfxs lqx jflb (contains soy, shellfish, sesame)
// lhgkrc djjk dskjpq pctjm xzb srmsh tvtsbxb sbjnrn smtthp drfgh lqb fzhvcz txts gxhc ksdgk khqsk jmtzqjs fjqlm lqx hxxb cvv spnzjj tjm vgbl qvqf kjdrd zbkbgp mvbxt dcgpsq cjgm msfxp rtvgv thfqk llfdjz mcmr ckptp lbvlp lbvgfq pgnpx zstptg mhzdz dtpkz spfzpm jffhm vgh qsbsr lrhtp ttmr pgxzdxf vhhj ksj rnptcf skkn nsgpf xhdq pknvxsb stfmsqc hdfrg gcj gcllv ffssl gtjhr nhqtzkn fhmgrhg rmrmhb ljkdr mcnzq bzjmn lkrnkm crlzb frsvq xbhmf dbkz qxmrqb hpvzlb jbvhl zlc vjbmbz mxd bhzqc kcck ztvfvhz (contains peanuts, shellfish, wheat)
// rrbk mcnzq sxmsxx qnmt blkh smtthp skxd hpvzlb vvcnht qxpmkdp ltxf srmsh cpzzfpz gtjhr bcchptf lmhqv mvbxt rmbk fjqlm jflb msfxp pdmg xhdq qxmrqb lrhtp dzdgl fhmgrhg skkn zbkbgp ktlttm bgqg llfdjz khqsk vrssb zcxfj hdfrg bcpgx pgnpx ndnq vxqrj lqb hmqhpzr xrmx jmtzqjs dcgpsq nvbrx mhzdz gcc hk xbngqsv ksdgk dgms scnlb ckptp mlvdvc kcck krllr vgh ffssl djjk xzb thfqk jmrdr nql lqx lbvgfq jvrn dbkz jbvhl txts (contains dairy, fish)
// ksdgk nsgpf ksj bgqg dpk dskjpq pclzcd fnsjrp vjbmbz kttg sbjnrn tjfgc jbvhl fhhcv pchzb hplt vnrmm ljkdr kqpbzn skkn jzdhlj txts chjx khqsk kpcv bzjmn pgnpx srmsh rzvpm ttmr cljq nql rnptcf hdfrg ndnq kcck kjdrd qsbsr gpzq nqkggbpq rmbk ffssl pknvxsb zdjcvfc crlzb pctjm smtthp mvbxt tnjnr thfqk nvbrx xzb xtzhq scljtv (contains shellfish, sesame, peanuts)
// tvtsbxb qnmt vgbl srmsh xbngqsv kpcv ckptp xtzhq mhzdz smtthp fjqlm fzmzs bgqg qsbsr fhhcv cjgm qxmrqb krllr xhqsl msfxp qpnt nqkggbpq vnrmm lmn spnzjj zbkbgp cdqrg blkh mcnzq gdhpvgz skkn thfqk dzdgl qnzljfj jrfzs jphll ffssl jvpsllhl ksdgk fzhvcz pgnpx lhgkrc xnhgg pclzcd xplz cprbsmpx lzpcq rnptcf pnhrz qrvdjvg hxxb kttg jffhm jbvhl cdblnb lqb hplt rtvgv nvbrx rrbk grkrz dtpkz dskjpq skxd hk bgzm jvljzbh vvcnht ndnq gbtss pdmg lbvlp lmhqv frsvq lkrnkm rzpdmp xbhmf zxtgf gxhc khqsk sbtkm gcj vhhj clbqr vzsjm sbjnrn (contains fish, sesame, dairy)
// smjk zxtgf tzbrg gxhc fxlbcb xrmx gdhpvgz ndnq flxvrh gcj cdqrg qxpmkdp cprbsmpx kpcv dsvl fhmgrhg nvbrx jdcvff jvpsllhl pchzb drfgh dskjpq lmhqv tjm srmsh jflb vcfxs nql zlc jphll ltxf vhhj pgxzdxf frsvq dpk vnrmm xhdq vxqrj kkggp fhhcv rvvcm pnhrz ttmr txts bcpgx km skkn qqzqd cbshx qrvdjvg qnmt rmrmhb lrhtp jmtzqjs vrssb mdzbsft xqxgx xzb pgnpx zbkbgp ksdgk krllr dbkz lqx bcchptf jlpzn lzpcq lqb htk tjfgc (contains wheat)
// mhzdz nvbrx bhzqc kjdrd vxqrj zstptg zkkxgzm bgzm jvpsllhl ttmr nhqtzkn vvcnht sbjnrn lrnxgns mdzbsft qvqf scnlb pgnpx gdhpvgz gbtss gcj lbvlp cljq gcllv smtthp scljtv rrbk cdblnb ksdgk pctjm tjfgc xzb sxmsxx sklm mvbxt mcmr hdfrg khqsk xbhmf dskjpq tvdqr jrfzs lkrnkm frsvq drfgh srmsh xqxgx zxtgf xhqsl jflb nqkggbpq qpnt fhmgrhg vzsjm tnjnr gxhc lmn rvvcm jzdhlj rzvpm xnhgg gdvts dcgpsq hplt (contains wheat)
// fzhvcz jvljzbh sxmsxx vxqrj grkrz lmn clbqr spnzjj qnmt xbngqsv dcgpsq pgnpx lmhqv jtq lzpcq xzgst xrvhc lhgkrc zkkxgzm hmqhpzr qxpmkdp gdvts ttmr dgms gxhc xzb ckptp sbjnrn rmbk nsgpf tjfgc ksdgk hxxb zdjcvfc jvpsllhl fnsjrp fxlbcb vjbmbz jzdhlj mcmr vhhj qpnt jdcvff lrhtp jmrdr khqsk kttg thfqk hk nqkggbpq jf scnlb dskjpq zcxfj zbkbgp crlzb ksj spfzpm gtjhr lkrnkm bcchptf mlvdvc gcc mvbxt crfvzpt ztvfvhz km qvqf mxd rrbk djjk skxd jmtzqjs srmsh bhzqc vnrmm bcpgx dzdgl kjdrd (contains eggs, shellfish, fish)
// pknvxsb gdhpvgz xlchb fhhcv jffhm xtzhq hk lrhtp vgh htk rtvgv mhzdz zvth scljtv gtjhr kttg lbvgfq khqsk lhgkrc fxlbcb lkrnkm crfvzpt cdqrg ttmr bgqg zxtgf tlfjpc hdkc srmsh ztvfvhz nvbrx qxmrqb qpnt tvdqr fnsjrp mdzbsft ckptp smjk zbkbgp vcfxs mcnzq ndnq nqkggbpq nhqtzkn gbtss xzb rzvpm kcck clbqr gcc mlvdvc dsvl jvljzbh xzgst rmbk sbtkm jphll pgnpx bcchptf kpcv dskjpq zdjcvfc llfdjz zkkxgzm kkggp hplt gdvts sbjnrn dcgpsq hmqhpzr cjgm vxqrj nsgpf qqzqd rrbk bcpgx dgms pdmg jvpsllhl hdfrg jmrdr (contains eggs, wheat)
// qnzljfj rckbqrc srmsh kcck nvbrx ltxf qrvdjvg xrvhc kttg bcchptf rmrmhb xzb sxmsxx jbmq xtzhq pdmg pnhrz pknvxsb vgbl gpzq gcllv qqzqd jvljzbh kkggp hxxb cbshx vzsjm ztvfvhz rtvgv gtjhr bgzm vgh jdcvff pgnpx xplz ffssl dskjpq nhqtzkn dtpkz sbtkm dsvl pctjm lzpcq mcnzq zbkbgp rzpdmp grkrz scljtv tvtsbxb cljq qsbsr hplt nqkggbpq jffhm ksj khqsk gdhpvgz tzbrg cjgm bcpgx dgms hmqhpzr xrmx xhqsl (contains eggs)
// mvbxt jbmq sklm gcj jmrdr scnlb gtjhr gxhc fjqlm sbjnrn jzdhlj rmrmhb lhgkrc jflb xtzhq dskjpq jvljzbh lbvgfq ksdgk dbkz zxtgf dtpkz qrvdjvg lbvlp dzdgl qxpmkdp gdhpvgz gpzq hplt bhzqc xhqsl lrnxgns xrvhc rnptcf bzjmn mdzbsft mcnzq clbqr mxd xzgst txts vjbmbz fxlbcb zvth pdmg srmsh hk skkn tjm pgxzdxf bgzm zkkxgzm xzb xbhmf blkh smtthp lmhqv khqsk jdcvff xrmx fhmgrhg bcpgx mlvdvc tzbrg kmjvr scljtv dsvl rvvcm vvcnht jvrn ndnq grkrz zbkbgp pctjm jbvhl crlzb xbngqsv ckptp llfdjz pknvxsb nvbrx mcmr xplz rzvpm (contains soy, shellfish, peanuts)".to_string()
}
